/**
 * capture-seed.js
 * ─────────────────────────────────────────────────────────────────
 * Reads every current record from the database and regenerates
 * prisma/seed.js so it can restore your data on any fresh install.
 *
 * Usage:
 *   node prisma/capture-seed.js
 *
 * Then to restore data on a fresh DB:
 *   npx prisma db push
 *   npx prisma db seed
 * ─────────────────────────────────────────────────────────────────
 */

const { PrismaClient } = require('@prisma/client');
const fs   = require('fs');
const path = require('path');

const prisma = new PrismaClient();

async function main() {
  console.log('📦 Reading current database records...\n');

  // ── Fetch all tables ──────────────────────────────────────────
  const [users, speakers, topics, lectures] = await Promise.all([
    prisma.user.findMany(),
    prisma.speaker.findMany(),
    prisma.topic.findMany(),
    prisma.lecture.findMany({ include: { topics: true } }),
  ]);

  console.log(`  ✅ Users:    ${users.length}`);
  console.log(`  ✅ Speakers: ${speakers.length}`);
  console.log(`  ✅ Topics:   ${topics.length}`);
  console.log(`  ✅ Lectures: ${lectures.length}\n`);

  // ── Helper: format a JS value for code output ─────────────────
  const fmt = (v) => {
    if (v === null || v === undefined) return 'null';
    if (v instanceof Date)             return `new Date('${v.toISOString()}')`;
    if (typeof v === 'string')         return JSON.stringify(v);
    if (typeof v === 'number')         return String(v);
    if (typeof v === 'boolean')        return String(v);
    return JSON.stringify(v);
  };

  // ── Helper: build upsert block ────────────────────────────────
  const upsertUser = (u) => `
  await prisma.user.upsert({
    where:  { email: ${fmt(u.email)} },
    update: {},
    create: {
      name:            ${fmt(u.name)},
      email:           ${fmt(u.email)},
      password:        ${fmt(u.password)},   // already hashed
      role:            ${fmt(u.role)},
    },
  });`;

  const upsertSpeaker = (s) => `
  await prisma.speaker.upsert({
    where:  { id: ${s.id} },
    update: { name: ${fmt(s.name)}, bio: ${fmt(s.bio)}, image: ${fmt(s.image)} },
    create: { name: ${fmt(s.name)}, bio: ${fmt(s.bio)}, image: ${fmt(s.image)} },
  });`;

  const upsertTopic = (t) => `
  await prisma.topic.upsert({
    where:  { name: ${fmt(t.name)} },
    update: {},
    create: { name: ${fmt(t.name)} },
  });`;

  const upsertLecture = (l) => {
    const topicConnects = l.topics.map(t => `{ name: ${fmt(t.name)} }`).join(', ');
    return `
  await prisma.lecture.upsert({
    where:  { id: ${l.id} },
    update: {
      title:       ${fmt(l.title)},
      description: ${fmt(l.description)},
      videoUrl:    ${fmt(l.videoUrl)},
      language:    ${fmt(l.language)},
      date:        ${fmt(l.date)},
      speaker:     { connect: { id: ${l.speakerId} } },
      topics:      { set: [${topicConnects}] },
    },
    create: {
      title:       ${fmt(l.title)},
      description: ${fmt(l.description)},
      videoUrl:    ${fmt(l.videoUrl)},
      language:    ${fmt(l.language)},
      date:        ${fmt(l.date)},
      speaker:     { connect: { id: ${l.speakerId} } },
      topics:      { connect: [${topicConnects}] },
    },
  });`;
  };

  // ── Build the seed.js file content ───────────────────────────
  const seedContent = `/**
 * seed.js  –  AUTO-GENERATED by capture-seed.js
 * Generated at: ${new Date().toISOString()}
 * Records: ${users.length} users | ${speakers.length} speakers | ${topics.length} topics | ${lectures.length} lectures
 *
 * Run this seeder:
 *   npx prisma db seed
 */

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {

  // ── Users ─────────────────────────────────────────────────────
  // Note: passwords are already bcrypt-hashed – no re-hashing needed.
${users.map(upsertUser).join('\n')}

  // ── Speakers ──────────────────────────────────────────────────
${speakers.map(upsertSpeaker).join('\n')}

  // ── Topics ────────────────────────────────────────────────────
${topics.map(upsertTopic).join('\n')}

  // ── Lectures (must come after speakers + topics) ──────────────
${lectures.map(upsertLecture).join('\n')}

  console.log('✅ Seeding complete!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
`;

  // ── Write file ─────────────────────────────────────────────────
  const outputPath = path.join(__dirname, 'seed.js');
  fs.writeFileSync(outputPath, seedContent, 'utf8');

  console.log(`✅ seed.js has been regenerated at:\n   ${outputPath}`);
  console.log('\nTo restore on a fresh database run:');
  console.log('  npx prisma db push');
  console.log('  npx prisma db seed\n');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
