/**
 * seed.js  –  AUTO-GENERATED by capture-seed.js
 * Generated at: 2026-05-07T04:36:35.029Z
 * Records: 1 users | 4 speakers | 2 topics | 0 lectures
 *
 * Run this seeder:
 *   npx prisma db seed
 */

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {

  // ── Users ─────────────────────────────────────────────────────
  // Note: passwords are already bcrypt-hashed – no re-hashing needed.

  await prisma.user.upsert({
    where:  { email: "admin@ilmhub.com" },
    update: {},
    create: {
      name:            "Admin",
      email:           "admin@ilmhub.com",
      password:        "$2b$12$i9y/CpS3ikYGHfnhaGoMl.TTvaSd4y9.Nr1eUWS4PDSZ1XCgBEudi",   // already hashed
      role:            "admin",
    },
  });

  // ── Speakers ──────────────────────────────────────────────────

  await prisma.speaker.upsert({
    where:  { id: 4 },
    update: { name: "Allama Raja Nasir Abbas", bio: "Raja Nasir Abbas Jafri (Urdu: راجہ ناصر عباس جعفری) is a Pakistani politician and member of the Senate of Pakistan from Punjab, Pakistan. He is a Shia Muslim cleric and Chairman of Muslimeen Pakistan. He is serving as the Leader of the opposition in the Senate of Pakistan nominated by Imran Khan, the Former Prime Minister of Pakistan since 19 January 2026.", image: "/uploads/1778128264220.jfif" },
    create: { name: "Allama Raja Nasir Abbas", bio: "Raja Nasir Abbas Jafri (Urdu: راجہ ناصر عباس جعفری) is a Pakistani politician and member of the Senate of Pakistan from Punjab, Pakistan. He is a Shia Muslim cleric and Chairman of Muslimeen Pakistan. He is serving as the Leader of the opposition in the Senate of Pakistan nominated by Imran Khan, the Former Prime Minister of Pakistan since 19 January 2026.", image: "/uploads/1778128264220.jfif" },
  });

  await prisma.speaker.upsert({
    where:  { id: 5 },
    update: { name: "Allama Syed Jawad Naqvi", bio: "Allama Syed Jawad Naqvi[a] (born 1963) is a Pakistani Islamic scholar, religious leader and Preacher who is the founder and chancellor of Jamia Urwat-ul-Wusqa in Lahore and many Islamic schools. A leading Shia theorist of Pakistan and worldwide, Naqvi founded the monthly religious magazine Masharab-e-Naab.", image: "/uploads/1778128332190.jfif" },
    create: { name: "Allama Syed Jawad Naqvi", bio: "Allama Syed Jawad Naqvi[a] (born 1963) is a Pakistani Islamic scholar, religious leader and Preacher who is the founder and chancellor of Jamia Urwat-ul-Wusqa in Lahore and many Islamic schools. A leading Shia theorist of Pakistan and worldwide, Naqvi founded the monthly religious magazine Masharab-e-Naab.", image: "/uploads/1778128332190.jfif" },
  });

  await prisma.speaker.upsert({
    where:  { id: 6 },
    update: { name: "Allama Syed Shehanshah Hussain Naqvi", bio: "Syed Shehanshah Hussain Naqvi has underlined the need for the Muslims to forge unity, putting aside their differences to successfully fail the agendas of imperialist forces. He has emphasized the need for unity and fraternity among Sunni-Shia Muslims.", image: "/uploads/1778128405876.jfif" },
    create: { name: "Allama Syed Shehanshah Hussain Naqvi", bio: "Syed Shehanshah Hussain Naqvi has underlined the need for the Muslims to forge unity, putting aside their differences to successfully fail the agendas of imperialist forces. He has emphasized the need for unity and fraternity among Sunni-Shia Muslims.", image: "/uploads/1778128405876.jfif" },
  });

  await prisma.speaker.upsert({
    where:  { id: 7 },
    update: { name: "Allama Arif Hussain al-Hussaini", bio: "Allama Arif Hussain al-Hussaini (1946–1988) was a prominent Pakistani Twelver Shia scholar, leader of Millat-e-Jafaria Pakistan (from 1984), and a key advocate for Shia-Sunni unity. A devotee of Imam Khomeini, he promoted revolutionary Islamic ideals and was assassinated in Peshawar on August 5, 1988. He is revered as \"Shaheed-e-Quaid\".", image: "/uploads/1778128494887.jfif" },
    create: { name: "Allama Arif Hussain al-Hussaini", bio: "Allama Arif Hussain al-Hussaini (1946–1988) was a prominent Pakistani Twelver Shia scholar, leader of Millat-e-Jafaria Pakistan (from 1984), and a key advocate for Shia-Sunni unity. A devotee of Imam Khomeini, he promoted revolutionary Islamic ideals and was assassinated in Peshawar on August 5, 1988. He is revered as \"Shaheed-e-Quaid\".", image: "/uploads/1778128494887.jfif" },
  });

  // ── Topics ────────────────────────────────────────────────────

  await prisma.topic.upsert({
    where:  { name: "Spirituality" },
    update: {},
    create: { name: "Spirituality" },
  });

  await prisma.topic.upsert({
    where:  { name: "History" },
    update: {},
    create: { name: "History" },
  });

  // ── Lectures (must come after speakers + topics) ──────────────


  console.log('✅ Seeding complete!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
